### ISSUE TITLE
problem in runtime

### ISSUE THREAD

**Issue by yousofkakhki** [blutorange/lotsOfBSGdx#4]
hi i am facing
06-15 11:17:15.956 29477-29477/de.homelab.madgaksha E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: de.homelab.madgaksha, PID: 29477
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{de.homelab.madgaksha/de.homelab.madgaksha.AndroidLauncher}: java.util.MissingResourceException: Can't find resource for bundle 'de.homelab.madgaksha.i18n.main_en_US', key ''

**Comment by yousofkakhki** [comment]
still facing the error please help
api which i have tested:19
`FATAL EXCEPTION: main
                                                 Process: de.homelab.madgaksha, PID: 5301
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{de.homelab.madgaksha/de.homelab.madgaksha.AndroidLauncher}: java.util.MissingResourceException: Can't find resource for bundle 'de.homelab.madgaksha.i18n.main_en_US', key ''
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.util.MissingResourceException: Can't find resource for bundle 'de.homelab.madgaksha.i18n.main_en_US', key ''
                                                     at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
                                                     at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
                                                     at java.util.ResourceBundle.getBundle(ResourceBundle.java:159)
                                                     at de.homelab.madgaksha.i18n.I18n.init(I18n.java:36)
                                                     at de.homelab.madgaksha.Game.<init>(Game.java:133)
                                                     at de.homelab.madgaksha.AndroidLauncher.onCreate(AndroidLauncher.java:18)
                                                     at android.app.Activity.performCreate(Activity.java:5231)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:136) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                     at dalvik.system.NativeStart.main(Native Method) `

**Comment by blutorange** [comment]
I might look into support for Android at some time, but for now, this only works on the desktop.
